//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.02 at 01:16:04 PM CEST 
//


package hr.dns.epp.contact;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for domainNum complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="domainNum"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="inZone" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="notInZone" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="inGrace" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domainNum", namespace = "http://www.dns.hr/epp/hr-1.0", propOrder = {
        "total",
        "inZone",
        "notInZone",
        "inGrace"
})
public class DomainNum {

    /**
     * Gets the value of the total property.
     */
    public long getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     */
    public void setTotal(long value) {
        this.total = value;
    }

    /**
     * Gets the value of the inZone property.
     */
    public long getInZone() {
        return inZone;
    }

    /**
     * Sets the value of the inZone property.
     */
    public void setInZone(long value) {
        this.inZone = value;
    }

    /**
     * Gets the value of the notInZone property.
     */
    public long getNotInZone() {
        return notInZone;
    }

    /**
     * Sets the value of the notInZone property.
     */
    public void setNotInZone(long value) {
        this.notInZone = value;
    }

    /**
     * Gets the value of the inGrace property.
     */
    public long getInGrace() {
        return inGrace;
    }

    /**
     * Sets the value of the inGrace property.
     */
    public void setInGrace(long value) {
        this.inGrace = value;
    }

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0")
    @XmlSchemaType(name = "unsignedInt")
    protected long total;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0")
    @XmlSchemaType(name = "unsignedInt")
    protected long inZone;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0")
    @XmlSchemaType(name = "unsignedInt")
    protected long notInZone;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0")
    @XmlSchemaType(name = "unsignedInt")
    protected long inGrace;

}
