//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.02 at 01:16:04 PM CEST 
//


package hr.dns.epp.contact;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for registrarData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="registrarData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="in" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="voice" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *         &lt;element name="registryMails" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/&gt;
 *         &lt;element name="account" type="{http://www.dns.hr/epp/hr-1.0}registrarAccount"/&gt;
 *         &lt;element name="postalInfo" type="{http://www.dns.hr/epp/hr-1.0}registrarPostalInfo"/&gt;
 *         &lt;element name="eppAccess" type="{http://www.dns.hr/epp/hr-1.0}eppAccess" minOccurs="0"/&gt;
 *         &lt;element name="domainNum" type="{http://www.dns.hr/epp/hr-1.0}domainNum"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registrarData", namespace = "http://www.dns.hr/epp/hr-1.0", propOrder = {

})
public class RegistrarData {

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the in property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIn() {
        return in;
    }

    /**
     * Sets the value of the in property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIn(String value) {
        this.in = value;
    }

    /**
     * Gets the value of the voice property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVoice() {
        return voice;
    }

    /**
     * Sets the value of the voice property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVoice(String value) {
        this.voice = value;
    }

    /**
     * Gets the value of the fax property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the registryMails property.
     */
    public int getRegistryMails() {
        return registryMails;
    }

    /**
     * Sets the value of the registryMails property.
     */
    public void setRegistryMails(int value) {
        this.registryMails = value;
    }

    /**
     * Gets the value of the account property.
     *
     * @return possible object is
     * {@link RegistrarAccount }
     */
    public RegistrarAccount getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     *
     * @param value allowed object is
     *              {@link RegistrarAccount }
     */
    public void setAccount(RegistrarAccount value) {
        this.account = value;
    }

    /**
     * Gets the value of the postalInfo property.
     *
     * @return possible object is
     * {@link RegistrarPostalInfo }
     */
    public RegistrarPostalInfo getPostalInfo() {
        return postalInfo;
    }

    /**
     * Sets the value of the postalInfo property.
     *
     * @param value allowed object is
     *              {@link RegistrarPostalInfo }
     */
    public void setPostalInfo(RegistrarPostalInfo value) {
        this.postalInfo = value;
    }

    /**
     * Gets the value of the eppAccess property.
     *
     * @return possible object is
     * {@link EppAccess }
     */
    public EppAccess getEppAccess() {
        return eppAccess;
    }

    /**
     * Sets the value of the eppAccess property.
     *
     * @param value allowed object is
     *              {@link EppAccess }
     */
    public void setEppAccess(EppAccess value) {
        this.eppAccess = value;
    }

    /**
     * Gets the value of the domainNum property.
     *
     * @return possible object is
     * {@link DomainNum }
     */
    public DomainNum getDomainNum() {
        return domainNum;
    }

    /**
     * Sets the value of the domainNum property.
     *
     * @param value allowed object is
     *              {@link DomainNum }
     */
    public void setDomainNum(DomainNum value) {
        this.domainNum = value;
    }

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String name;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String email;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String in;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String voice;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String fax;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0")
    @XmlSchemaType(name = "unsignedShort")
    protected int registryMails;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    protected RegistrarAccount account;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    protected RegistrarPostalInfo postalInfo;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0")
    protected EppAccess eppAccess;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    protected DomainNum domainNum;

}
