//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.02 at 01:16:04 PM CEST 
//


package hr.dns.epp.contact;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for registrarPostalInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="registrarPostalInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="cc" type="{urn:ietf:params:xml:ns:contact-1.0}ccType"/&gt;
 *         &lt;element name="pc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registrarPostalInfo", namespace = "http://www.dns.hr/epp/hr-1.0", propOrder = {
        "street",
        "city",
        "cc",
        "pc"
})
public class RegistrarPostalInfo {

    /**
     * Gets the value of the street property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the city property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the cc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCc() {
        return cc;
    }

    /**
     * Sets the value of the cc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCc(String value) {
        this.cc = value;
    }

    /**
     * Gets the value of the pc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPc() {
        return pc;
    }

    /**
     * Sets the value of the pc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPc(String value) {
        this.pc = value;
    }

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String street;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String city;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String cc;

    @XmlElement(namespace = "http://www.dns.hr/epp/hr-1.0", required = true)
    protected String pc;

}
