//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package hr.dns.epp.contact;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for registrarData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="registrarData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="in" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="voice" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="registryMails" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="account" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="postalInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="eppAccess" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="domainNum" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registrarData", propOrder = {

})
public class RegistrarData {

    @XmlElement(required = true)
    protected Object name;
    @XmlElement(required = true)
    protected Object email;
    @XmlElement(required = true)
    protected Object in;
    protected Object voice;
    protected Object fax;
    @XmlElement(required = true)
    protected Object registryMails;
    @XmlElement(required = true)
    protected Object account;
    @XmlElement(required = true)
    protected Object postalInfo;
    protected Object eppAccess;
    @XmlElement(required = true)
    protected Object domainNum;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setName(Object value) {
        this.name = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEmail(Object value) {
        this.email = value;
    }

    /**
     * Gets the value of the in property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIn() {
        return in;
    }

    /**
     * Sets the value of the in property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIn(Object value) {
        this.in = value;
    }

    /**
     * Gets the value of the voice property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVoice() {
        return voice;
    }

    /**
     * Sets the value of the voice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVoice(Object value) {
        this.voice = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFax(Object value) {
        this.fax = value;
    }

    /**
     * Gets the value of the registryMails property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRegistryMails() {
        return registryMails;
    }

    /**
     * Sets the value of the registryMails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRegistryMails(Object value) {
        this.registryMails = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAccount(Object value) {
        this.account = value;
    }

    /**
     * Gets the value of the postalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPostalInfo() {
        return postalInfo;
    }

    /**
     * Sets the value of the postalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPostalInfo(Object value) {
        this.postalInfo = value;
    }

    /**
     * Gets the value of the eppAccess property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEppAccess() {
        return eppAccess;
    }

    /**
     * Sets the value of the eppAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEppAccess(Object value) {
        this.eppAccess = value;
    }

    /**
     * Gets the value of the domainNum property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDomainNum() {
        return domainNum;
    }

    /**
     * Sets the value of the domainNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDomainNum(Object value) {
        this.domainNum = value;
    }

}
