//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.secdns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chgType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="chgType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="maxSigLife" type="{urn:ietf:params:xml:ns:secDNS-1.1}maxSigLifeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chgType", propOrder = {
        "maxSigLife"
})
public class ChgType {

    /**
     * Gets the value of the maxSigLife property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getMaxSigLife() {
        return maxSigLife;
    }

    /**
     * Sets the value of the maxSigLife property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMaxSigLife(Integer value) {
        this.maxSigLife = value;
    }

    protected Integer maxSigLife;

}
