//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.secdns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for dsDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dsDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="keyTag" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="alg" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="digestType" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="digest" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
 *         &lt;element name="keyData" type="{urn:ietf:params:xml:ns:secDNS-1.1}keyDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dsDataType", propOrder = {
    "keyTag",
    "alg",
    "digestType",
    "digest",
    "keyData"
})
public class DsDataType {

    @XmlSchemaType(name = "unsignedShort")
    protected int keyTag;
    @XmlSchemaType(name = "unsignedByte")
    protected short alg;
    @XmlSchemaType(name = "unsignedByte")
    protected short digestType;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] digest;
    protected KeyDataType keyData;

    /**
     * Gets the value of the keyTag property.
     * 
     */
    public int getKeyTag() {
        return keyTag;
    }

    /**
     * Sets the value of the keyTag property.
     * 
     */
    public void setKeyTag(int value) {
        this.keyTag = value;
    }

    /**
     * Gets the value of the alg property.
     * 
     */
    public short getAlg() {
        return alg;
    }

    /**
     * Sets the value of the alg property.
     * 
     */
    public void setAlg(short value) {
        this.alg = value;
    }

    /**
     * Gets the value of the digestType property.
     * 
     */
    public short getDigestType() {
        return digestType;
    }

    /**
     * Sets the value of the digestType property.
     * 
     */
    public void setDigestType(short value) {
        this.digestType = value;
    }

    /**
     * Gets the value of the digest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getDigest() {
        return digest;
    }

    /**
     * Sets the value of the digest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigest(byte[] value) {
        this.digest = value;
    }

    /**
     * Gets the value of the keyData property.
     * 
     * @return
     *     possible object is
     *     {@link KeyDataType }
     *     
     */
    public KeyDataType getKeyData() {
        return keyData;
    }

    /**
     * Sets the value of the keyData property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyDataType }
     *     
     */
    public void setKeyData(KeyDataType value) {
        this.keyData = value;
    }

}
