//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.secdns;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ietf.epp.secdns package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InfData_QNAME = new QName("urn:ietf:params:xml:ns:secDNS-1.1", "infData");
    private final static QName _Create_QNAME = new QName("urn:ietf:params:xml:ns:secDNS-1.1", "create");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ietf.epp.secdns
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DsOrKeyType }
     * 
     */
    public DsOrKeyType createDsOrKeyType() {
        return new DsOrKeyType();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link RemType }
     * 
     */
    public RemType createRemType() {
        return new RemType();
    }

    /**
     * Create an instance of {@link ChgType }
     * 
     */
    public ChgType createChgType() {
        return new ChgType();
    }

    /**
     * Create an instance of {@link KeyDataType }
     * 
     */
    public KeyDataType createKeyDataType() {
        return new KeyDataType();
    }

    /**
     * Create an instance of {@link DsDataType }
     * 
     */
    public DsDataType createDsDataType() {
        return new DsDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DsOrKeyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:secDNS-1.1", name = "infData")
    public JAXBElement<DsOrKeyType> createInfData(DsOrKeyType value) {
        return new JAXBElement<DsOrKeyType>(_InfData_QNAME, DsOrKeyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DsOrKeyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:secDNS-1.1", name = "create")
    public JAXBElement<DsOrKeyType> createCreate(DsOrKeyType value) {
        return new JAXBElement<DsOrKeyType>(_Create_QNAME, DsOrKeyType.class, null, value);
    }

}
