//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.secdns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for remType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="remType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="all" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="dsData" type="{urn:ietf:params:xml:ns:secDNS-1.1}dsDataType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="keyData" type="{urn:ietf:params:xml:ns:secDNS-1.1}keyDataType" maxOccurs="unbounded"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "remType", propOrder = {
        "keyDatas",
        "dsDatas",
        "all"
})
public class RemType {

    /**
     * Gets the value of the keyDatas property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyDatas property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyDatas().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyDataType }
     */
    public List<KeyDataType> getKeyDatas() {
        if (keyDatas == null) {
            keyDatas = new ArrayList<KeyDataType>();
        }
        return this.keyDatas;
    }

    /**
     * Gets the value of the dsDatas property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dsDatas property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDsDatas().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DsDataType }
     */
    public List<DsDataType> getDsDatas() {
        if (dsDatas == null) {
            dsDatas = new ArrayList<DsDataType>();
        }
        return this.dsDatas;
    }

    /**
     * Gets the value of the all property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isAll() {
        return all;
    }

    /**
     * Sets the value of the all property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setAll(Boolean value) {
        this.all = value;
    }

    @XmlElement(name = "keyData")
    protected List<KeyDataType> keyDatas;

    @XmlElement(name = "dsData")
    protected List<DsDataType> dsDatas;

    protected Boolean all;

}
