//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.secdns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rem" type="{urn:ietf:params:xml:ns:secDNS-1.1}remType" minOccurs="0"/>
 *         &lt;element name="add" type="{urn:ietf:params:xml:ns:secDNS-1.1}dsOrKeyType" minOccurs="0"/>
 *         &lt;element name="chg" type="{urn:ietf:params:xml:ns:secDNS-1.1}chgType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="urgent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateType", propOrder = {
    "rem",
    "add",
    "chg"
})
@XmlRootElement(name = "update")
public class Update {

    protected RemType rem;
    protected DsOrKeyType add;
    protected ChgType chg;
    @XmlAttribute(name = "urgent")
    protected Boolean urgent;

    /**
     * Gets the value of the rem property.
     * 
     * @return
     *     possible object is
     *     {@link RemType }
     *     
     */
    public RemType getRem() {
        return rem;
    }

    /**
     * Sets the value of the rem property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemType }
     *     
     */
    public void setRem(RemType value) {
        this.rem = value;
    }

    /**
     * Gets the value of the add property.
     * 
     * @return
     *     possible object is
     *     {@link DsOrKeyType }
     *     
     */
    public DsOrKeyType getAdd() {
        return add;
    }

    /**
     * Sets the value of the add property.
     * 
     * @param value
     *     allowed object is
     *     {@link DsOrKeyType }
     *     
     */
    public void setAdd(DsOrKeyType value) {
        this.add = value;
    }

    /**
     * Gets the value of the chg property.
     * 
     * @return
     *     possible object is
     *     {@link ChgType }
     *     
     */
    public ChgType getChg() {
        return chg;
    }

    /**
     * Sets the value of the chg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChgType }
     *     
     */
    public void setChg(ChgType value) {
        this.chg = value;
    }

    /**
     * Gets the value of the urgent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUrgent() {
        if (urgent == null) {
            return false;
        } else {
            return urgent;
        }
    }

    /**
     * Sets the value of the urgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUrgent(Boolean value) {
        this.urgent = value;
    }

}
