//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contactAttrType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="contactAttrType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="admin"/&gt;
 *     &lt;enumeration value="billing"/&gt;
 *     &lt;enumeration value="tech"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "contactAttrType")
@XmlEnum
public enum ContactAttrType {

    @XmlEnumValue("admin")
    ADMIN("admin"),
    @XmlEnumValue("billing")
    BILLING("billing"),
    @XmlEnumValue("tech")
    TECH("tech");

    ContactAttrType(String v) {
        value = v;
    }

    public static ContactAttrType fromValue(String v) {
        for (ContactAttrType c : ContactAttrType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

    private final String value;

}
