//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.domain;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for createType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="createType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{urn:ietf:params:xml:ns:eppcom-1.0}labelType"/&gt;
 *         &lt;element name="period" type="{urn:ietf:params:xml:ns:domain-1.0}periodType" minOccurs="0"/&gt;
 *         &lt;element name="ns" type="{urn:ietf:params:xml:ns:domain-1.0}nsType" minOccurs="0"/&gt;
 *         &lt;element name="registrant" type="{urn:ietf:params:xml:ns:eppcom-1.0}clIDType" minOccurs="0"/&gt;
 *         &lt;element name="contact" type="{urn:ietf:params:xml:ns:domain-1.0}contactType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="authInfo" type="{urn:ietf:params:xml:ns:domain-1.0}authInfoType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createType", propOrder = {
        "name",
        "period",
        "ns",
        "registrant",
        "contacts",
        "authInfo"
})
@XmlRootElement(name = "create")
public class Create {

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the period property.
     *
     * @return possible object is
     * {@link PeriodType }
     */
    public PeriodType getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     *
     * @param value allowed object is
     *              {@link PeriodType }
     */
    public void setPeriod(PeriodType value) {
        this.period = value;
    }

    /**
     * Gets the value of the ns property.
     *
     * @return possible object is
     * {@link NsType }
     */
    public NsType getNs() {
        return ns;
    }

    /**
     * Sets the value of the ns property.
     *
     * @param value allowed object is
     *              {@link NsType }
     */
    public void setNs(NsType value) {
        this.ns = value;
    }

    /**
     * Gets the value of the registrant property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRegistrant() {
        return registrant;
    }

    /**
     * Sets the value of the registrant property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRegistrant(String value) {
        this.registrant = value;
    }

    /**
     * Gets the value of the contacts property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contacts property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContacts().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactType }
     */
    public List<ContactType> getContacts() {
        if (contacts == null) {
            contacts = new ArrayList<ContactType>();
        }
        return this.contacts;
    }

    /**
     * Gets the value of the authInfo property.
     *
     * @return possible object is
     * {@link AuthInfoType }
     */
    public AuthInfoType getAuthInfo() {
        return authInfo;
    }

    /**
     * Sets the value of the authInfo property.
     *
     * @param value allowed object is
     *              {@link AuthInfoType }
     */
    public void setAuthInfo(AuthInfoType value) {
        this.authInfo = value;
    }

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;

    protected PeriodType period;

    protected NsType ns;

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String registrant;

    @XmlElement(name = "contact")
    protected List<ContactType> contacts;

    @XmlElement(required = true)
    protected AuthInfoType authInfo;

}
