//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.domain;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for infoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="infoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{urn:ietf:params:xml:ns:domain-1.0}infoNameType"/&gt;
 *         &lt;element name="authInfo" type="{urn:ietf:params:xml:ns:domain-1.0}authInfoType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infoType", propOrder = {
        "name",
        "authInfo"
})
@XmlRootElement(name = "info")
public class Info {

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link InfoNameType }
     */
    public InfoNameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link InfoNameType }
     */
    public void setName(InfoNameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the authInfo property.
     *
     * @return possible object is
     * {@link AuthInfoType }
     */
    public AuthInfoType getAuthInfo() {
        return authInfo;
    }

    /**
     * Sets the value of the authInfo property.
     *
     * @param value allowed object is
     *              {@link AuthInfoType }
     */
    public void setAuthInfo(AuthInfoType value) {
        this.authInfo = value;
    }

    @XmlElement(required = true)
    protected InfoNameType name;

    protected AuthInfoType authInfo;

}
