//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.ietf.epp.domain package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ietf.epp.domain
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreData }
     */
    public CreData createCreData() {
        return new CreData();
    }

    /**
     * Create an instance of {@link Update }
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link AddRemType }
     */
    public AddRemType createAddRemType() {
        return new AddRemType();
    }

    /**
     * Create an instance of {@link ChgType }
     */
    public ChgType createChgType() {
        return new ChgType();
    }

    /**
     * Create an instance of {@link PanData }
     */
    public PanData createPanData() {
        return new PanData();
    }

    /**
     * Create an instance of {@link PaNameType }
     */
    public PaNameType createPaNameType() {
        return new PaNameType();
    }

    /**
     * Create an instance of {@link InfData }
     */
    public InfData createInfData() {
        return new InfData();
    }

    /**
     * Create an instance of {@link StatusType }
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link ContactType }
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link NsType }
     */
    public NsType createNsType() {
        return new NsType();
    }

    /**
     * Create an instance of {@link AuthInfoType }
     */
    public AuthInfoType createAuthInfoType() {
        return new AuthInfoType();
    }

    /**
     * Create an instance of {@link Check }
     */
    public Check createCheck() {
        return new Check();
    }

    /**
     * Create an instance of {@link RenData }
     */
    public RenData createRenData() {
        return new RenData();
    }

    /**
     * Create an instance of {@link Delete }
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link Transfer }
     */
    public Transfer createTransfer() {
        return new Transfer();
    }

    /**
     * Create an instance of {@link PeriodType }
     */
    public PeriodType createPeriodType() {
        return new PeriodType();
    }

    /**
     * Create an instance of {@link TrnData }
     */
    public TrnData createTrnData() {
        return new TrnData();
    }

    /**
     * Create an instance of {@link ChkData }
     */
    public ChkData createChkData() {
        return new ChkData();
    }

    /**
     * Create an instance of {@link CheckType }
     */
    public CheckType createCheckType() {
        return new CheckType();
    }

    /**
     * Create an instance of {@link Create }
     */
    public Create createCreate() {
        return new Create();
    }

    /**
     * Create an instance of {@link Renew }
     */
    public Renew createRenew() {
        return new Renew();
    }

    /**
     * Create an instance of {@link Info }
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link InfoNameType }
     */
    public InfoNameType createInfoNameType() {
        return new InfoNameType();
    }

    /**
     * Create an instance of {@link AuthInfoChgType }
     */
    public AuthInfoChgType createAuthInfoChgType() {
        return new AuthInfoChgType();
    }

    /**
     * Create an instance of {@link HostAttrType }
     */
    public HostAttrType createHostAttrType() {
        return new HostAttrType();
    }

    /**
     * Create an instance of {@link CheckNameType }
     */
    public CheckNameType createCheckNameType() {
        return new CheckNameType();
    }

}
