//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.03.17 at 05:43:45 PM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ietf:params:xml:ns:domain-1.0", //
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, //
		xmlns = @javax.xml.bind.annotation.XmlNs(prefix = "domain", namespaceURI = "urn:ietf:params:xml:ns:domain-1.0"))
package org.ietf.epp.domain;

