//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.host;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for infDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="infDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{urn:ietf:params:xml:ns:eppcom-1.0}labelType"/&gt;
 *         &lt;element name="roid" type="{urn:ietf:params:xml:ns:eppcom-1.0}roidType"/&gt;
 *         &lt;element name="status" type="{urn:ietf:params:xml:ns:host-1.0}statusType" maxOccurs="7"/&gt;
 *         &lt;element name="addr" type="{urn:ietf:params:xml:ns:host-1.0}addrType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="clID" type="{urn:ietf:params:xml:ns:eppcom-1.0}clIDType"/&gt;
 *         &lt;element name="crID" type="{urn:ietf:params:xml:ns:eppcom-1.0}clIDType"/&gt;
 *         &lt;element name="crDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="upID" type="{urn:ietf:params:xml:ns:eppcom-1.0}clIDType" minOccurs="0"/&gt;
 *         &lt;element name="upDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="trDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infDataType", propOrder = {
        "name",
        "roid",
        "statuses",
        "addrs",
        "clID",
        "crID",
        "crDate",
        "upID",
        "upDate",
        "trDate"
})
@XmlRootElement(name = "infData")
public class InfData {

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the roid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoid() {
        return roid;
    }

    /**
     * Sets the value of the roid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoid(String value) {
        this.roid = value;
    }

    /**
     * Gets the value of the statuses property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statuses property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatuses().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusType }
     */
    public List<StatusType> getStatuses() {
        if (statuses == null) {
            statuses = new ArrayList<StatusType>();
        }
        return this.statuses;
    }

    /**
     * Gets the value of the addrs property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addrs property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddrs().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddrType }
     */
    public List<AddrType> getAddrs() {
        if (addrs == null) {
            addrs = new ArrayList<AddrType>();
        }
        return this.addrs;
    }

    /**
     * Gets the value of the clID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClID() {
        return clID;
    }

    /**
     * Sets the value of the clID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClID(String value) {
        this.clID = value;
    }

    /**
     * Gets the value of the crID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCrID() {
        return crID;
    }

    /**
     * Sets the value of the crID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCrID(String value) {
        this.crID = value;
    }

    /**
     * Gets the value of the crDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getCrDate() {
        return crDate;
    }

    /**
     * Sets the value of the crDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setCrDate(XMLGregorianCalendar value) {
        this.crDate = value;
    }

    /**
     * Gets the value of the upID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUpID() {
        return upID;
    }

    /**
     * Sets the value of the upID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUpID(String value) {
        this.upID = value;
    }

    /**
     * Gets the value of the upDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getUpDate() {
        return upDate;
    }

    /**
     * Sets the value of the upDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setUpDate(XMLGregorianCalendar value) {
        this.upDate = value;
    }

    /**
     * Gets the value of the trDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getTrDate() {
        return trDate;
    }

    /**
     * Sets the value of the trDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setTrDate(XMLGregorianCalendar value) {
        this.trDate = value;
    }

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String roid;

    @XmlElement(name = "status", required = true)
    protected List<StatusType> statuses;

    @XmlElement(name = "addr")
    protected List<AddrType> addrs;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String clID;

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String crID;

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar crDate;

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String upID;

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar upDate;

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar trDate;

}
