//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.host;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ietf.epp.host package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Info_QNAME = new QName("urn:ietf:params:xml:ns:host-1.0", "info");
    private final static QName _Delete_QNAME = new QName("urn:ietf:params:xml:ns:host-1.0", "delete");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ietf.epp.host
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreData }
     * 
     */
    public CreData createCreData() {
        return new CreData();
    }

    /**
     * Create an instance of {@link ChkData }
     * 
     */
    public ChkData createChkData() {
        return new ChkData();
    }

    /**
     * Create an instance of {@link CheckType }
     * 
     */
    public CheckType createCheckType() {
        return new CheckType();
    }

    /**
     * Create an instance of {@link Create }
     * 
     */
    public Create createCreate() {
        return new Create();
    }

    /**
     * Create an instance of {@link AddrType }
     * 
     */
    public AddrType createAddrType() {
        return new AddrType();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link AddRemType }
     * 
     */
    public AddRemType createAddRemType() {
        return new AddRemType();
    }

    /**
     * Create an instance of {@link ChgType }
     * 
     */
    public ChgType createChgType() {
        return new ChgType();
    }

    /**
     * Create an instance of {@link PanData }
     * 
     */
    public PanData createPanData() {
        return new PanData();
    }

    /**
     * Create an instance of {@link PaNameType }
     * 
     */
    public PaNameType createPaNameType() {
        return new PaNameType();
    }

    /**
     * Create an instance of {@link InfData }
     * 
     */
    public InfData createInfData() {
        return new InfData();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link Check }
     * 
     */
    public Check createCheck() {
        return new Check();
    }

    /**
     * Create an instance of {@link SNameType }
     * 
     */
    public SNameType createSNameType() {
        return new SNameType();
    }

    /**
     * Create an instance of {@link CheckNameType }
     * 
     */
    public CheckNameType createCheckNameType() {
        return new CheckNameType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:host-1.0", name = "info")
    public JAXBElement<SNameType> createInfo(SNameType value) {
        return new JAXBElement<SNameType>(_Info_QNAME, SNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:host-1.0", name = "delete")
    public JAXBElement<SNameType> createDelete(SNameType value) {
        return new JAXBElement<SNameType>(_Delete_QNAME, SNameType.class, null, value);
    }

}
