//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.host;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.ietf.epp.epp.TrIDType;


/**
 * <p>Java class for panDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="panDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{urn:ietf:params:xml:ns:host-1.0}paNameType"/>
 *         &lt;element name="paTRID" type="{urn:ietf:params:xml:ns:epp-1.0}trIDType"/>
 *         &lt;element name="paDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "panDataType", propOrder = {
    "name",
    "paTRID",
    "paDate"
})
@XmlRootElement(name = "panData")
public class PanData {

    @XmlElement(required = true)
    protected PaNameType name;
    @XmlElement(required = true)
    protected TrIDType paTRID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar paDate;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link PaNameType }
     *     
     */
    public PaNameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaNameType }
     *     
     */
    public void setName(PaNameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the paTRID property.
     * 
     * @return
     *     possible object is
     *     {@link TrIDType }
     *     
     */
    public TrIDType getPaTRID() {
        return paTRID;
    }

    /**
     * Sets the value of the paTRID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrIDType }
     *     
     */
    public void setPaTRID(TrIDType value) {
        this.paTRID = value;
    }

    /**
     * Gets the value of the paDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaDate() {
        return paDate;
    }

    /**
     * Sets the value of the paDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaDate(XMLGregorianCalendar value) {
        this.paDate = value;
    }

}
