//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.contact;

import org.ietf.epp.eppcom.ReasonType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for checkType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="checkType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{urn:ietf:params:xml:ns:contact-1.0}checkIDType"/&gt;
 *         &lt;element name="reason" type="{urn:ietf:params:xml:ns:eppcom-1.0}reasonType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "checkType", propOrder = {
        "id",
        "reason"
})
public class CheckType {

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link CheckIDType }
     */
    public CheckIDType getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link CheckIDType }
     */
    public void setId(CheckIDType value) {
        this.id = value;
    }

    /**
     * Gets the value of the reason property.
     *
     * @return possible object is
     * {@link ReasonType }
     */
    public ReasonType getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     *
     * @param value allowed object is
     *              {@link ReasonType }
     */
    public void setReason(ReasonType value) {
        this.reason = value;
    }

    @XmlElement(required = true)
    protected CheckIDType id;

    protected ReasonType reason;

}
