//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.contact;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for chgPostalInfoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="chgPostalInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{urn:ietf:params:xml:ns:contact-1.0}postalLineType" minOccurs="0"/&gt;
 *         &lt;element name="org" type="{urn:ietf:params:xml:ns:contact-1.0}optPostalLineType" minOccurs="0"/&gt;
 *         &lt;element name="addr" type="{urn:ietf:params:xml:ns:contact-1.0}addrType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" use="required" type="{urn:ietf:params:xml:ns:contact-1.0}postalInfoEnumType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chgPostalInfoType", propOrder = {
        "name",
        "org",
        "addr"
})
public class ChgPostalInfoType {

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the org property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrg() {
        return org;
    }

    /**
     * Sets the value of the org property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrg(String value) {
        this.org = value;
    }

    /**
     * Gets the value of the addr property.
     *
     * @return possible object is
     * {@link AddrType }
     */
    public AddrType getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     *
     * @param value allowed object is
     *              {@link AddrType }
     */
    public void setAddr(AddrType value) {
        this.addr = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link PostalInfoEnumType }
     */
    public PostalInfoEnumType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link PostalInfoEnumType }
     */
    public void setType(PostalInfoEnumType value) {
        this.type = value;
    }

    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String name;

    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String org;

    protected AddrType addr;

    @XmlAttribute(name = "type", required = true)
    protected PostalInfoEnumType type;

}
