//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.contact;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ietf.epp.contact package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Info_QNAME = new QName("urn:ietf:params:xml:ns:contact-1.0", "info");
    private final static QName _Transfer_QNAME = new QName("urn:ietf:params:xml:ns:contact-1.0", "transfer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ietf.epp.contact
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreData }
     * 
     */
    public CreData createCreData() {
        return new CreData();
    }

    /**
     * Create an instance of {@link AuthIDType }
     * 
     */
    public AuthIDType createAuthIDType() {
        return new AuthIDType();
    }

    /**
     * Create an instance of {@link TrnData }
     * 
     */
    public TrnData createTrnData() {
        return new TrnData();
    }

    /**
     * Create an instance of {@link ChkData }
     * 
     */
    public ChkData createChkData() {
        return new ChkData();
    }

    /**
     * Create an instance of {@link CheckType }
     * 
     */
    public CheckType createCheckType() {
        return new CheckType();
    }

    /**
     * Create an instance of {@link Create }
     * 
     */
    public Create createCreate() {
        return new Create();
    }

    /**
     * Create an instance of {@link PostalInfoType }
     * 
     */
    public PostalInfoType createPostalInfoType() {
        return new PostalInfoType();
    }

    /**
     * Create an instance of {@link E164Type }
     * 
     */
    public E164Type createE164Type() {
        return new E164Type();
    }

    /**
     * Create an instance of {@link AuthInfoType }
     * 
     */
    public AuthInfoType createAuthInfoType() {
        return new AuthInfoType();
    }

    /**
     * Create an instance of {@link DiscloseType }
     * 
     */
    public DiscloseType createDiscloseType() {
        return new DiscloseType();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link AddRemType }
     * 
     */
    public AddRemType createAddRemType() {
        return new AddRemType();
    }

    /**
     * Create an instance of {@link ChgType }
     * 
     */
    public ChgType createChgType() {
        return new ChgType();
    }

    /**
     * Create an instance of {@link PanData }
     * 
     */
    public PanData createPanData() {
        return new PanData();
    }

    /**
     * Create an instance of {@link PaCLIDType }
     * 
     */
    public PaCLIDType createPaCLIDType() {
        return new PaCLIDType();
    }

    /**
     * Create an instance of {@link InfData }
     * 
     */
    public InfData createInfData() {
        return new InfData();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link Check }
     * 
     */
    public Check createCheck() {
        return new Check();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link IntLocType }
     * 
     */
    public IntLocType createIntLocType() {
        return new IntLocType();
    }

    /**
     * Create an instance of {@link ChgPostalInfoType }
     * 
     */
    public ChgPostalInfoType createChgPostalInfoType() {
        return new ChgPostalInfoType();
    }

    /**
     * Create an instance of {@link AddrType }
     * 
     */
    public AddrType createAddrType() {
        return new AddrType();
    }

    /**
     * Create an instance of {@link CheckIDType }
     * 
     */
    public CheckIDType createCheckIDType() {
        return new CheckIDType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:contact-1.0", name = "info")
    public JAXBElement<AuthIDType> createInfo(AuthIDType value) {
        return new JAXBElement<AuthIDType>(_Info_QNAME, AuthIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:contact-1.0", name = "transfer")
    public JAXBElement<AuthIDType> createTransfer(AuthIDType value) {
        return new JAXBElement<AuthIDType>(_Transfer_QNAME, AuthIDType.class, null, value);
    }

}
