//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.contact;

import org.ietf.epp.epp.TrIDType;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for panDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="panDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{urn:ietf:params:xml:ns:contact-1.0}paCLIDType"/&gt;
 *         &lt;element name="paTRID" type="{urn:ietf:params:xml:ns:epp-1.0}trIDType"/&gt;
 *         &lt;element name="paDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "panDataType", propOrder = {
        "id",
        "paTRID",
        "paDate"
})
@XmlRootElement(name = "panData")
public class PanData {

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link PaCLIDType }
     */
    public PaCLIDType getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link PaCLIDType }
     */
    public void setId(PaCLIDType value) {
        this.id = value;
    }

    /**
     * Gets the value of the paTRID property.
     *
     * @return possible object is
     * {@link TrIDType }
     */
    public TrIDType getPaTRID() {
        return paTRID;
    }

    /**
     * Sets the value of the paTRID property.
     *
     * @param value allowed object is
     *              {@link TrIDType }
     */
    public void setPaTRID(TrIDType value) {
        this.paTRID = value;
    }

    /**
     * Gets the value of the paDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getPaDate() {
        return paDate;
    }

    /**
     * Sets the value of the paDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setPaDate(XMLGregorianCalendar value) {
        this.paDate = value;
    }

    @XmlElement(required = true)
    protected PaCLIDType id;

    @XmlElement(required = true)
    protected TrIDType paTRID;

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar paDate;

}
