//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.contact;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.ietf.epp.eppcom.TrStatusType;


/**
 * <p>Java class for trnDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trnDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{urn:ietf:params:xml:ns:eppcom-1.0}clIDType"/>
 *         &lt;element name="trStatus" type="{urn:ietf:params:xml:ns:eppcom-1.0}trStatusType"/>
 *         &lt;element name="reID" type="{urn:ietf:params:xml:ns:eppcom-1.0}clIDType"/>
 *         &lt;element name="reDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="acID" type="{urn:ietf:params:xml:ns:eppcom-1.0}clIDType"/>
 *         &lt;element name="acDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trnDataType", propOrder = {
    "id",
    "trStatus",
    "reID",
    "reDate",
    "acID",
    "acDate"
})
@XmlRootElement(name = "trnData")
public class TrnData {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected TrStatusType trStatus;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String reID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reDate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String acID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar acDate;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the trStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TrStatusType }
     *     
     */
    public TrStatusType getTrStatus() {
        return trStatus;
    }

    /**
     * Sets the value of the trStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrStatusType }
     *     
     */
    public void setTrStatus(TrStatusType value) {
        this.trStatus = value;
    }

    /**
     * Gets the value of the reID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReID() {
        return reID;
    }

    /**
     * Sets the value of the reID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReID(String value) {
        this.reID = value;
    }

    /**
     * Gets the value of the reDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReDate() {
        return reDate;
    }

    /**
     * Sets the value of the reDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReDate(XMLGregorianCalendar value) {
        this.reDate = value;
    }

    /**
     * Gets the value of the acID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcID() {
        return acID;
    }

    /**
     * Sets the value of the acID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcID(String value) {
        this.acID = value;
    }

    /**
     * Gets the value of the acDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcDate() {
        return acDate;
    }

    /**
     * Sets the value of the acDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcDate(XMLGregorianCalendar value) {
        this.acDate = value;
    }

}
