//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.contact;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for updateType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="updateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{urn:ietf:params:xml:ns:eppcom-1.0}clIDType"/&gt;
 *         &lt;element name="add" type="{urn:ietf:params:xml:ns:contact-1.0}addRemType" minOccurs="0"/&gt;
 *         &lt;element name="rem" type="{urn:ietf:params:xml:ns:contact-1.0}addRemType" minOccurs="0"/&gt;
 *         &lt;element name="chg" type="{urn:ietf:params:xml:ns:contact-1.0}chgType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateType", propOrder = {
        "id",
        "add",
        "rem",
        "chg"
})
@XmlRootElement(name = "update")
public class Update {

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the add property.
     *
     * @return possible object is
     * {@link AddRemType }
     */
    public AddRemType getAdd() {
        return add;
    }

    /**
     * Sets the value of the add property.
     *
     * @param value allowed object is
     *              {@link AddRemType }
     */
    public void setAdd(AddRemType value) {
        this.add = value;
    }

    /**
     * Gets the value of the rem property.
     *
     * @return possible object is
     * {@link AddRemType }
     */
    public AddRemType getRem() {
        return rem;
    }

    /**
     * Sets the value of the rem property.
     *
     * @param value allowed object is
     *              {@link AddRemType }
     */
    public void setRem(AddRemType value) {
        this.rem = value;
    }

    /**
     * Gets the value of the chg property.
     *
     * @return possible object is
     * {@link ChgType }
     */
    public ChgType getChg() {
        return chg;
    }

    /**
     * Sets the value of the chg property.
     *
     * @param value allowed object is
     *              {@link ChgType }
     */
    public void setChg(ChgType value) {
        this.chg = value;
    }

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String id;

    protected AddRemType add;

    protected AddRemType rem;

    protected ChgType chg;

}
