//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 10:13:52 AM CET 
//


package org.ietf.epp.epp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dcpRetentionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dcpRetentionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="business" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="indefinite" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="legal" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="none" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="stated" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dcpRetentionType", namespace = "urn:ietf:params:xml:ns:epp-1.0", propOrder = {
    "stated",
    "none",
    "legal",
    "indefinite",
    "business"
})
public class DcpRetentionType {

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected Object stated;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected Object none;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected Object legal;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected Object indefinite;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected Object business;

    /**
     * Gets the value of the stated property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStated() {
        return stated;
    }

    /**
     * Sets the value of the stated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStated(Object value) {
        this.stated = value;
    }

    /**
     * Gets the value of the none property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNone() {
        return none;
    }

    /**
     * Sets the value of the none property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNone(Object value) {
        this.none = value;
    }

    /**
     * Gets the value of the legal property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLegal() {
        return legal;
    }

    /**
     * Sets the value of the legal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLegal(Object value) {
        this.legal = value;
    }

    /**
     * Gets the value of the indefinite property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIndefinite() {
        return indefinite;
    }

    /**
     * Sets the value of the indefinite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIndefinite(Object value) {
        this.indefinite = value;
    }

    /**
     * Gets the value of the business property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBusiness() {
        return business;
    }

    /**
     * Sets the value of the business property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBusiness(Object value) {
        this.business = value;
    }

}
