//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.epp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dcpRecipientType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dcpRecipientType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="other" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="ours" type="{urn:ietf:params:xml:ns:epp-1.0}dcpOursType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="public" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="same" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="unrelated" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dcpRecipientType", propOrder = {
    "other",
    "ours",
    "_public",
    "same",
    "unrelated"
})
public class DcpRecipientType {

    protected Object other;
    protected List<DcpOursType> ours;
    @XmlElement(name = "public")
    protected Object _public;
    protected Object same;
    protected Object unrelated;

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOther(Object value) {
        this.other = value;
    }

    /**
     * Gets the value of the ours property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ours property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOurs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcpOursType }
     * 
     * 
     */
    public List<DcpOursType> getOurs() {
        if (ours == null) {
            ours = new ArrayList<DcpOursType>();
        }
        return this.ours;
    }

    /**
     * Gets the value of the public property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPublic() {
        return _public;
    }

    /**
     * Sets the value of the public property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPublic(Object value) {
        this._public = value;
    }

    /**
     * Gets the value of the same property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSame() {
        return same;
    }

    /**
     * Sets the value of the same property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSame(Object value) {
        this.same = value;
    }

    /**
     * Gets the value of the unrelated property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUnrelated() {
        return unrelated;
    }

    /**
     * Sets the value of the unrelated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUnrelated(Object value) {
        this.unrelated = value;
    }

}
