//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 10:13:52 AM CET 
//


package org.ietf.epp.epp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dcpStatementType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="dcpStatementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="purpose" type="{urn:ietf:params:xml:ns:epp-1.0}dcpPurposeType"/&gt;
 *         &lt;element name="recipient" type="{urn:ietf:params:xml:ns:epp-1.0}dcpRecipientType"/&gt;
 *         &lt;element name="retention" type="{urn:ietf:params:xml:ns:epp-1.0}dcpRetentionType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dcpStatementType", namespace = "urn:ietf:params:xml:ns:epp-1.0", propOrder = {
        "purpose",
        "recipient",
        "retention"
})
public class DcpStatementType {

    /**
     * Gets the value of the purpose property.
     *
     * @return possible object is
     * {@link DcpPurposeType }
     */
    public DcpPurposeType getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     *
     * @param value allowed object is
     *              {@link DcpPurposeType }
     */
    public void setPurpose(DcpPurposeType value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the recipient property.
     *
     * @return possible object is
     * {@link DcpRecipientType }
     */
    public DcpRecipientType getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     *
     * @param value allowed object is
     *              {@link DcpRecipientType }
     */
    public void setRecipient(DcpRecipientType value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the retention property.
     *
     * @return possible object is
     * {@link DcpRetentionType }
     */
    public DcpRetentionType getRetention() {
        return retention;
    }

    /**
     * Sets the value of the retention property.
     *
     * @param value allowed object is
     *              {@link DcpRetentionType }
     */
    public void setRetention(DcpRetentionType value) {
        this.retention = value;
    }

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0", required = true)
    protected DcpPurposeType purpose;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0", required = true)
    protected DcpRecipientType recipient;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0", required = true)
    protected DcpRetentionType retention;

}
