//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 10:13:52 AM CET 
//


package org.ietf.epp.epp;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for eppType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="eppType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="greeting" type="{urn:ietf:params:xml:ns:epp-1.0}greetingType"/&gt;
 *         &lt;element name="hello" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="command" type="{urn:ietf:params:xml:ns:epp-1.0}commandType"/&gt;
 *         &lt;element name="response" type="{urn:ietf:params:xml:ns:epp-1.0}responseType"/&gt;
 *         &lt;element name="extension" type="{urn:ietf:params:xml:ns:epp-1.0}extAnyType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eppType", namespace = "urn:ietf:params:xml:ns:epp-1.0", propOrder = {
        "extension",
        "response",
        "command",
        "hello",
        "greeting"
})
@XmlRootElement(name = "epp", namespace = "urn:ietf:params:xml:ns:epp-1.0")
public class Epp {

    /**
     * Gets the value of the extension property.
     *
     * @return possible object is
     * {@link ExtAnyType }
     */
    public ExtAnyType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     *
     * @param value allowed object is
     *              {@link ExtAnyType }
     */
    public void setExtension(ExtAnyType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the response property.
     *
     * @return possible object is
     * {@link ResponseType }
     */
    public ResponseType getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     *
     * @param value allowed object is
     *              {@link ResponseType }
     */
    public void setResponse(ResponseType value) {
        this.response = value;
    }

    /**
     * Gets the value of the command property.
     *
     * @return possible object is
     * {@link CommandType }
     */
    public CommandType getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     *
     * @param value allowed object is
     *              {@link CommandType }
     */
    public void setCommand(CommandType value) {
        this.command = value;
    }

    /**
     * Gets the value of the hello property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHello() {
        return hello;
    }

    /**
     * Sets the value of the hello property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHello(String value) {
        this.hello = value;
    }

    /**
     * Gets the value of the greeting property.
     *
     * @return possible object is
     * {@link GreetingType }
     */
    public GreetingType getGreeting() {
        return greeting;
    }

    /**
     * Sets the value of the greeting property.
     *
     * @param value allowed object is
     *              {@link GreetingType }
     */
    public void setGreeting(GreetingType value) {
        this.greeting = value;
    }

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected ExtAnyType extension;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected ResponseType response;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected CommandType command;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected String hello;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected GreetingType greeting;

}
