//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 05:43:45 PM CET 
//


package org.ietf.epp.epp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eppType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eppType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="greeting" type="{urn:ietf:params:xml:ns:epp-1.0}greetingType"/>
 *         &lt;element name="hello" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="command" type="{urn:ietf:params:xml:ns:epp-1.0}commandType"/>
 *         &lt;element name="response" type="{urn:ietf:params:xml:ns:epp-1.0}responseType"/>
 *         &lt;element name="extension" type="{urn:ietf:params:xml:ns:epp-1.0}extAnyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eppType", propOrder = {
    "extension",
    "response",
    "command",
    "hello",
    "greeting"
})
@XmlRootElement(name = "epp")
public class Epp {

    protected ExtAnyType extension;
    protected ResponseType response;
    protected CommandType command;
    protected Object hello;
    protected GreetingType greeting;

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtAnyType }
     *     
     */
    public ExtAnyType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtAnyType }
     *     
     */
    public void setExtension(ExtAnyType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseType }
     *     
     */
    public ResponseType getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseType }
     *     
     */
    public void setResponse(ResponseType value) {
        this.response = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link CommandType }
     *     
     */
    public CommandType getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandType }
     *     
     */
    public void setCommand(CommandType value) {
        this.command = value;
    }

    /**
     * Gets the value of the hello property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getHello() {
        return hello;
    }

    /**
     * Sets the value of the hello property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setHello(Object value) {
        this.hello = value;
    }

    /**
     * Gets the value of the greeting property.
     * 
     * @return
     *     possible object is
     *     {@link GreetingType }
     *     
     */
    public GreetingType getGreeting() {
        return greeting;
    }

    /**
     * Sets the value of the greeting property.
     * 
     * @param value
     *     allowed object is
     *     {@link GreetingType }
     *     
     */
    public void setGreeting(GreetingType value) {
        this.greeting = value;
    }

}
