//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 10:13:52 AM CET 
//


package org.ietf.epp.epp;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for greetingType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="greetingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="svID" type="{urn:ietf:params:xml:ns:epp-1.0}sIDType"/&gt;
 *         &lt;element name="svDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="svcMenu" type="{urn:ietf:params:xml:ns:epp-1.0}svcMenuType"/&gt;
 *         &lt;element name="dcp" type="{urn:ietf:params:xml:ns:epp-1.0}dcpType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "greetingType", namespace = "urn:ietf:params:xml:ns:epp-1.0", propOrder = {
        "svID",
        "svDate",
        "svcMenu",
        "dcp"
})
public class GreetingType {

    /**
     * Gets the value of the svID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSvID() {
        return svID;
    }

    /**
     * Sets the value of the svID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSvID(String value) {
        this.svID = value;
    }

    /**
     * Gets the value of the svDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getSvDate() {
        return svDate;
    }

    /**
     * Sets the value of the svDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setSvDate(XMLGregorianCalendar value) {
        this.svDate = value;
    }

    /**
     * Gets the value of the svcMenu property.
     *
     * @return possible object is
     * {@link SvcMenuType }
     */
    public SvcMenuType getSvcMenu() {
        return svcMenu;
    }

    /**
     * Sets the value of the svcMenu property.
     *
     * @param value allowed object is
     *              {@link SvcMenuType }
     */
    public void setSvcMenu(SvcMenuType value) {
        this.svcMenu = value;
    }

    /**
     * Gets the value of the dcp property.
     *
     * @return possible object is
     * {@link DcpType }
     */
    public DcpType getDcp() {
        return dcp;
    }

    /**
     * Sets the value of the dcp property.
     *
     * @param value allowed object is
     *              {@link DcpType }
     */
    public void setDcp(DcpType value) {
        this.dcp = value;
    }

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String svID;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar svDate;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0", required = true)
    protected SvcMenuType svcMenu;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0", required = true)
    protected DcpType dcp;

}
