//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 10:13:52 AM CET 
//


package org.ietf.epp.epp;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for msgQType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="msgQType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="qDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="msg" type="{urn:ietf:params:xml:ns:epp-1.0}mixedMsgType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" /&gt;
 *       &lt;attribute name="id" use="required" type="{urn:ietf:params:xml:ns:eppcom-1.0}minTokenType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "msgQType", namespace = "urn:ietf:params:xml:ns:epp-1.0", propOrder = {
        "qDate",
        "msg"
})
public class MsgQType {

    /**
     * Gets the value of the qDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getQDate() {
        return qDate;
    }

    /**
     * Sets the value of the qDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setQDate(XMLGregorianCalendar value) {
        this.qDate = value;
    }

    /**
     * Gets the value of the msg property.
     *
     * @return possible object is
     * {@link MixedMsgType }
     */
    public MixedMsgType getMsg() {
        return msg;
    }

    /**
     * Sets the value of the msg property.
     *
     * @param value allowed object is
     *              {@link MixedMsgType }
     */
    public void setMsg(MixedMsgType value) {
        this.msg = value;
    }

    /**
     * Gets the value of the count property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar qDate;

    @XmlElement(namespace = "urn:ietf:params:xml:ns:epp-1.0")
    protected MixedMsgType msg;

    @XmlAttribute(name = "count", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger count;

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;

}
