//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 10:13:52 AM CET 
//


package org.ietf.epp.epp;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for pollType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="pollType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="op" use="required" type="{urn:ietf:params:xml:ns:epp-1.0}pollOpType" /&gt;
 *       &lt;attribute name="msgID" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pollType", namespace = "urn:ietf:params:xml:ns:epp-1.0")
public class PollType {

    /**
     * Gets the value of the op property.
     *
     * @return possible object is
     * {@link PollOpType }
     */
    public PollOpType getOp() {
        return op;
    }

    /**
     * Sets the value of the op property.
     *
     * @param value allowed object is
     *              {@link PollOpType }
     */
    public void setOp(PollOpType value) {
        this.op = value;
    }

    /**
     * Gets the value of the msgID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMsgID(String value) {
        this.msgID = value;
    }

    @XmlAttribute(name = "op", required = true)
    protected PollOpType op;

    @XmlAttribute(name = "msgID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String msgID;

}
