//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 10:13:52 AM CET 
//


package org.ietf.epp.epp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transferOpType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="transferOpType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="approve"/&gt;
 *     &lt;enumeration value="cancel"/&gt;
 *     &lt;enumeration value="query"/&gt;
 *     &lt;enumeration value="reject"/&gt;
 *     &lt;enumeration value="request"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "transferOpType", namespace = "urn:ietf:params:xml:ns:epp-1.0")
@XmlEnum
public enum TransferOpType {

    @XmlEnumValue("approve")
    APPROVE("approve"),
    @XmlEnumValue("cancel")
    CANCEL("cancel"),
    @XmlEnumValue("query")
    QUERY("query"),
    @XmlEnumValue("reject")
    REJECT("reject"),
    @XmlEnumValue("request")
    REQUEST("request");

    TransferOpType(String v) {
        value = v;
    }

    public static TransferOpType fromValue(String v) {
        for (TransferOpType c : TransferOpType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

    private final String value;

}
